# Dockerfile - alpine
# https://github.com/openresty/docker-openresty

ARG RESTY_IMAGE_BASE="alpine"
ARG RESTY_IMAGE_TAG="3.8"

FROM ${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}

LABEL maintainer="Dmitry Kireev <dmitry@kireev.co>"

# Docker Build Arguments
ARG RESTY_VERSION="1.13.6.2"
ARG RESTY_OPENSSL_VERSION="1.0.2k"
ARG RESTY_PCRE_VERSION="8.42"
ARG RESTY_PAGESPEED_VERSION="1.13.35.2"
ARG RESTY_J="1"
ARG RESTY_CONFIG_OPTIONS="\
    --with-file-aio \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_geoip_module=dynamic \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_image_filter_module=dynamic \
    --with-http_mp4_module \
    --with-http_random_index_module \
    --with-http_realip_module \
    --with-http_secure_link_module \
    --with-http_slice_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_sub_module \
    --with-http_v2_module \
    --with-http_xslt_module=dynamic \
    --with-ipv6 \
    --with-mail \
    --with-mail_ssl_module \
    --with-md5-asm \
    --with-pcre-jit \
    --with-sha1-asm \
    --with-stream \
    --with-stream_ssl_module \
    --with-threads \
    --with-cc-opt=-fPIC \
    --with-cc-opt=-I/usr/include/apr-1 \
    "
ARG RESTY_CONFIG_OPTIONS_MORE=""

# These are not intended to be user-specified
ARG _RESTY_PAGESPEED_RELEASE="beta"
ARG _RESTY_CONFIG_DEPS="--add-module=/tmp/modpagespeed"

# 1) Install apk dependencies
# 2) Download and untar OpenSSL, PCRE, and OpenResty
# 3) Build OpenResty
# 4) Cleanup

RUN apk add --no-cache --virtual .build-deps \
        build-base \
        curl \
        bash \
        gperf \
        git \
        make \
        linux-headers \
        python \
        gd-dev \
        geoip-dev \
        libxslt-dev \
        perl-dev \
        readline-dev \
        zlib-dev \
        icu-dev \
        apr-dev \
        apr-util-dev \
        libjpeg-turbo-dev \
        apache2-dev \
        zlib-dev \
        libpng-dev \
        libressl-dev \
        pcre-dev \
    && apk add --no-cache \
        gd \
        geoip \
        libxslt \
        zlib \
        icu icu-libs \
        libgcc \
        pcre \
        libressl \
        libjpeg-turbo \
        apr \
        apr-util \
        icu-libs \
    \
    && cd /tmp \
    && curl -fSL https://openresty.org/download/openresty-${RESTY_VERSION}.tar.gz | tar -zx \
    && curl -fSL https://github.com/apache/incubator-pagespeed-ngx/archive/v${RESTY_PAGESPEED_VERSION}-${_RESTY_PAGESPEED_RELEASE}.tar.gz | tar -zx && mv /tmp/incubator-pagespeed-ngx-${RESTY_PAGESPEED_VERSION}-${_RESTY_PAGESPEED_RELEASE} /tmp/modpagespeed \
    && curl -fSL https://github.com/wodby/nginx-alpine-psol/releases/download/${RESTY_PAGESPEED_VERSION}/psol.tar.gz | tar -zx -C /tmp/modpagespeed \
    && cd /tmp/openresty-${RESTY_VERSION} \
    && LD_LIBRARY_PATH=/tmp/modpagespeed/usr/lib \
    && ./configure -j${RESTY_J} \
        ${_RESTY_CONFIG_DEPS} \
        ${RESTY_CONFIG_OPTIONS} \
        ${RESTY_CONFIG_OPTIONS_MORE} \
        --with-ld-opt='-Wl,-z,relro,--start-group -lapr-1 -laprutil-1 -licudata -licuuc -lpng -lturbojpeg -ljpeg' \
    && cd /tmp/openresty-${RESTY_VERSION} \
    && make -j${RESTY_J} \
    && make install\
    && apk del .build-deps \
    && rm -rf /tmp/* \
    && ln -sf /dev/stdout /usr/local/openresty/nginx/logs/access.log \
    && ln -sf /dev/stderr /usr/local/openresty/nginx/logs/error.log \
    && mkdir -p /var/cache/ngx_pagespeed \
    && chmod -R o+wr /var/cache/ngx_pagespeed

# Add additional binaries into PATH for convenience
ENV PATH=$PATH:/usr/local/openresty/luajit/bin/:/usr/local/openresty/nginx/sbin/:/usr/local/openresty/bin/

CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
